# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Unpack MOTIS (frontend)
  unarchive:
    src: https://github.com/public-transport/transitous/releases/download/motis-v2.0.4/motis-v2.0.4.tar.bz2
    dest: /opt/motis/
    remote_src: yes

- name: Install nginx
  apt:
    name: nginx

- name: Make sure nginx is running
  systemd:
    name: nginx.service
    state: started

- name: Create nginx cache directory
  file:
    path: /var/cache/nginx
    state: directory

- name: Install nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Install site config
  template:
    src: "transitous.conf.j2"
    dest: "/etc/nginx/sites-available/transitous.conf"

- name: Disable default site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable nginx sites
  file:
    src: "/etc/nginx/sites-available/transitous.conf"
    dest: "/etc/nginx/sites-enabled/transitous.conf"
    state: link

- name: Reload nginx
  systemd:
    name: nginx.service
    state: reloaded
